# arxivの学問領域の指定
subject: 'cat:eess.SY OR cat:eess.SP OR cat:cs.RO OR cat:cs.SY'

# 検索キーワード
keywords:
        navigation: 3
        planning: 3
        living: 1
        dynamic: 1
        robot: 2

# 通知の閾値
score_threshold: 0
